config/routes.rb
Frenzy::Application.routes.draw do
  root :to => 'questions#index'
  devise_for :users
  resources :questions do
    collection do
      get "free"
    end
    member do
      get "vote_for"
      get "vote_against"
    end
  end
  resources :answers do
  end
  
  resources :users, :only => [:show]
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  # Associations
  belongs_to :user, :counter_cache => true
  belongs_to :question, :counter_cache => true
  
  acts_as_voteable
end

app/models/question.rb
class Question < ActiveRecord::Base
  # Associations
  belongs_to :user, :counter_cache => true
  has_many :answers
  
  # scopes
  scope :free, lambda { where(["credit = 0 AND money = 0.00"]) }
  scope :paid, lambda { where(["credit <> 0 OR money <> 0.00"])}
  default_scope order("created_at DESC")
  
  acts_as_voteable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :remember_me
  attr_accessible :login, :username, :credit, :money, :about_me
  attr_accessible :authentication_token
  attr_accessor :login

  # Callbacks
  before_create :create_login
  before_create :ensure_authentication_token

  # Associations
  has_many :questions
  has_many :answers
  
  acts_as_voter

  protected
  def create_login
    if self.username.empty?
      email = self.email.split(/@/)
      login_taken = User.where(:username => email[0]).first
      self.username = email[0] unless login_taken
    end
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  scope :for_voter, lambda { |*args| where(["voter_id = ? AND voter_type = ?", args.first.id, args.first.class.name]) }
  scope :for_voteable, lambda { |*args| where(["voteable_id = ? AND voteable_type = ?", args.first.id, args.first.class.name]) }
  scope :recent, lambda { |*args| where(["created_at > ?", (args.first || 2.weeks.ago)]) }
  scope :descending, order("created_at DESC")

  belongs_to :voteable, :polymorphic => true
  belongs_to :voter, :polymorphic => true

  attr_accessible :vote, :voter, :voteable


  # Comment out the line below to allow multiple votes per user.
  validates_uniqueness_of :voteable_id, :scope => [:voteable_type, :voter_type, :voter_id]

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  respond_to :html
  
  def create
    question = Question.find params[:answer][:question_id]
    answer = current_user.answers.build(params[:answer])
    flash[:notice] = "Answer was successfully created." if answer.save
    respond_with(question)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user!
  layout :route_layout
  protect_from_forgery
  
  private
    def route_layout
      devise_controller? ? "welcome" : "application"
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  respond_to :html
  before_filter :vote_init, :only => [:vote_for, :vote_against]
  
  def index
    respond_with(@questions = Question.paid)
  end
  
  def free
    respond_with(@questions = Question.free)
  end
  
  def show
    respond_with(@question = Question.find(params[:id]))
  end
  
  def new
    respond_with(@question = Question.new)
  end
  
  def create
    @question = current_user.questions.build(params[:question])
    flash[:notice] = 'Question was successfully created.' if @question.save
    respond_with(@question)
  end
  
  def edit
    respond_with(@question = Question.find(params[:id]))
  end
  
  def update
    @question = current_user.questions.find(params[:id])
    flash[:notice] = 'Question was successfully updated.' if @question.update_attributes(params[:question])
    respond_with(@question)
  end
  
  def destroy
    
  end
  
  def vote_for
    if current_user.credit >= Settings.vote_for_limit and @voted != true
      if @voted == nil
        current_user.vote_for @question
      else
        current_user.vote_exclusively_against @question
      end
    end
  end
  
  def vote_against
    if current_user.credit >= Settings.vote_against_limit and @voted != false
      if @voted == nil
        current_user.vote_against @question
      else
        current_user.vote_exclusively_for @question
      end
    end
  end
  
  protected
    def vote_init
      @question = Question.select("id").find_by_id(params[:id])
      @voted = @question.trivalent_voted_by? current_user
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>迷乱</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="topbar" data-dropdown="dropdown">
    <div class="topbar-inner">
      <div class="container">
        <h3><a href="/">迷 乱</a></h3>
        <ul class="nav">
          <li class="active"><a href="/questions">悬赏</a></li>
          <li><a href="/questions/free">免费</a></li>
        </ul>
        <ul class="nav secondary-nav">
          <ul class="nav">
            <li><a href="/questions/new">提问</a></li>
          </ul>
          <li class="dropdown">
            <a href="" class="dropdown-toggle"><%= current_user.username %></a>
            <ul class="dropdown-menu">
              <li><%= link_to "个人主页", current_user %></li>
              <li><a href="#">充值</a></li>
              <li class="divider"></li>
              <li><%= link_to "登出", destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>迷乱</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="topbar" data-dropdown="dropdown">
    <div class="topbar-inner">
      <div class="container">
        <h3><a href="/">迷 乱</a></h3>
        <%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => {:class => "pull-right"}) do |f| %>
        <%= f.text_field :login, :class => "input-small", :placeholder => "Login" %>
        <%= f.password_field :password, :class => "input-small", :placeholder => "Password" %>
        <button class="btn" name="commit" type="submit">Sign in</button>
        <% end %>
      </div>
    </div>
  </div>
  <div class="container">
    <%= render "/devise/registrations/new" %>
  </div>
</body>
</html>

app/views/questions/free.html.erb
<div class="content">
  <div class="page-header">
    <h1>免费问题 <small>不积跬步，无以至千里</small></h1>
  </div>
  <div class="row">
    <div class="span12">
      <% @questions.each do |question| %>
        <%= div_for question do %>
          <h4><%=link_to question.title, question %></h4>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<div class="content">
  <div class="page-header">
    <h1>悬赏问题 <small>重赏之下，必有勇夫</small></h1>
  </div>
  <div class="row">
    <div class="span12">
      <% @questions.each do |question| %>
        <%= div_for question do %>
          <h4><%=link_to question.title, question %></h4>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="content">
  <div class="page-header">
    <h1>Ask Question <small>Supporting text or tagline</small></h1>
  </div>
  <div class="row">
    <div class="span12">
      <%= form_for(@question) do |f| %>
  		<fieldset>
  			<div class="clearfix">
  				<label for="text_area">标题</label>
  				<div class="input">
  					<%= f.text_field :title, :class => 'xxlarge' %>
  					<span class="help-block">必填，最多70个字</span>
  				</div>
  			</div>
  			<div class="clearfix">
  				<div class="input">
  					<%= f.text_area :content, :class => 'xxlarge' %>
  					<span class="help-block">可选，详细描述你的问题</span>
  				</div>
  			</div>
  			<div class="clearfix">
  				<label for="">积分</label>
  				<div class="input">
  					<%= f.text_field :credit, :class => 'span3' %>
  				</div>
  			</div>
  			<div class="clearfix">
  				<label for="">金钱</label>
  				<div class="input">
  					<%= f.select :money, 11.times.collect{|i| [i, i]}, {}, {:class => 'span3'} %> 元
  				</div>
  			</div>
  			<div class="actions">
  				<%= f.submit '提交', :class => "btn primary" %>
  				<button type="reset" class="btn">取消</button>
  			</div>
  		</fieldset>
  		<% end %>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class="content">
  <div class="page-header">
    <h1><%= @question.title %></h1>
  </div>
  <div class="row">
    <div class="span12">
      <div class="text">
        <%= @question.content %>
      </div>
    </div>
  </div>
</div>

<% if @question.answers_count > 0 %>
  <div class="header-block">
    <div class="page-header">
      <h1><%= @question.answers_count %> 个答案</h1>
    </div>
    <div class="row">
      <div class="span12">
        <% @question.answers.each do |answer| %>
          <%= div_for answer do %>
            <div class="text">
              <%= answer.content %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<div class="header-block">
  <div class="page-header">
    <h1>添加答案</h1>
  </div>
  <div class="row">
    <div class="span12">
      <%= form_for(Answer.new) do |f| %>
			  <%= f.hidden_field :question_id, :value => @question.id %>
				<div class="clearfix">
					<%= f.text_area :content, :class => 'span12' %>
				</div>
				<%= f.submit '提交', :class => "btn primary" %>
			<% end %>
    </div>
  </div>
</div>